// flow-typed signature: 4db6dd97347b6c748701de9ef7753abc
// flow-typed version: <<STUB>>/bl_v^1.2.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bl' {
  declare module.exports: any;
}
