// flow-typed signature: 8350bb507416e4f14dec7aa28caab71e
// flow-typed version: <<STUB>>/buffer-indexof_v1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-indexof'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-indexof' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buffer-indexof/bm' {
  declare module.exports: any;
}

declare module 'buffer-indexof/test/bm' {
  declare module.exports: any;
}

declare module 'buffer-indexof/test/multibyteneedle' {
  declare module.exports: any;
}

declare module 'buffer-indexof/test/partial-match' {
  declare module.exports: any;
}

declare module 'buffer-indexof/test/test-buffer-indexof' {
  declare module.exports: any;
}

declare module 'buffer-indexof/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buffer-indexof/bm.js' {
  declare module.exports: $Exports<'buffer-indexof/bm'>;
}
declare module 'buffer-indexof/index' {
  declare module.exports: $Exports<'buffer-indexof'>;
}
declare module 'buffer-indexof/index.js' {
  declare module.exports: $Exports<'buffer-indexof'>;
}
declare module 'buffer-indexof/test/bm.js' {
  declare module.exports: $Exports<'buffer-indexof/test/bm'>;
}
declare module 'buffer-indexof/test/multibyteneedle.js' {
  declare module.exports: $Exports<'buffer-indexof/test/multibyteneedle'>;
}
declare module 'buffer-indexof/test/partial-match.js' {
  declare module.exports: $Exports<'buffer-indexof/test/partial-match'>;
}
declare module 'buffer-indexof/test/test-buffer-indexof.js' {
  declare module.exports: $Exports<'buffer-indexof/test/test-buffer-indexof'>;
}
declare module 'buffer-indexof/test/test.js' {
  declare module.exports: $Exports<'buffer-indexof/test/test'>;
}
