// flow-typed signature: b57640b236f0fa316e4695d8fe828110
// flow-typed version: <<STUB>>/compression_v^1.7.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression' {
  declare module.exports: any;
}
