// flow-typed signature: 1e5782ecd9e0e8dbafdb5c29ece1d141
// flow-typed version: <<STUB>>/consume-until_v2.0.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'consume-until'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'consume-until' {
  import type {Readable} from 'stream';
  declare type Callback = (err: ?Error, data: ?Buffer) => void;
  declare module.exports: (Readable, Buffer, Callback) => void;
}
