// flow-typed signature: 2b78ae414a0465e96105867e2724f7a5
// flow-typed version: <<STUB>>/content-type-parser_v1.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'content-type-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'content-type-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'content-type-parser/lib/content-type-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'content-type-parser/lib/content-type-parser.js' {
  declare module.exports: $Exports<'content-type-parser/lib/content-type-parser'>;
}
