// flow-typed signature: 0d5c5ceefcdb0663982d848443e33a70
// flow-typed version: <<STUB>>/http-status-codes_v1.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-status-codes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-status-codes' {
  declare export function getStatusText(number): string;
}
