// flow-typed signature: f6ea4d5bbe6be55963eef598ec618a59
// flow-typed version: <<STUB>>/http-errors_v1.6.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'http-errors/index' {
  declare module.exports: $Exports<'http-errors'>;
}
declare module 'http-errors/index.js' {
  declare module.exports: $Exports<'http-errors'>;
}
