// flow-typed signature: 6c4833adec9f130124ca97eb587e4771
// flow-typed version: <<STUB>>/http-proxy_v^1.16.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-proxy' {
  declare module.exports: any;
}
