// flow-typed signature: 357498ce72c46993321252dfe372e703
// flow-typed version: <<STUB>>/negotiator_v^0.6.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'negotiator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'negotiator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'negotiator/lib/charset' {
  declare module.exports: any;
}

declare module 'negotiator/lib/encoding' {
  declare module.exports: any;
}

declare module 'negotiator/lib/language' {
  declare module.exports: any;
}

declare module 'negotiator/lib/mediaType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'negotiator/index' {
  declare module.exports: $Exports<'negotiator'>;
}
declare module 'negotiator/index.js' {
  declare module.exports: $Exports<'negotiator'>;
}
declare module 'negotiator/lib/charset.js' {
  declare module.exports: $Exports<'negotiator/lib/charset'>;
}
declare module 'negotiator/lib/encoding.js' {
  declare module.exports: $Exports<'negotiator/lib/encoding'>;
}
declare module 'negotiator/lib/language.js' {
  declare module.exports: $Exports<'negotiator/lib/language'>;
}
declare module 'negotiator/lib/mediaType.js' {
  declare module.exports: $Exports<'negotiator/lib/mediaType'>;
}
