// flow-typed signature: 3aaed64a2ccb678dcb24280d717fdf19
// flow-typed version: <<STUB>>/on-finished_v^2.3.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'on-finished'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'on-finished' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'on-finished/index' {
  declare module.exports: $Exports<'on-finished'>;
}
declare module 'on-finished/index.js' {
  declare module.exports: $Exports<'on-finished'>;
}
