// flow-typed signature: 0564455fee110032a38c7ba21288d403
// flow-typed version: <<STUB>>/on-headers_v^1.0.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'on-headers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'on-headers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'on-headers/index' {
  declare module.exports: $Exports<'on-headers'>;
}
declare module 'on-headers/index.js' {
  declare module.exports: $Exports<'on-headers'>;
}
