// flow-typed signature: 36831e9bd1f74bf66ed3ea95441fa993
// flow-typed version: <<STUB>>/parseurl_v^1.3.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parseurl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parseurl' {
  import type {IncomingMessage} from 'http';
  declare module.exports: (IncomingMessage) => URL;
}
