// flow-typed signature: e0ea51acca990a917f927b056018873e
// flow-typed version: <<STUB>>/send_v^0.16.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'send'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'send' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'send/index' {
  declare module.exports: $Exports<'send'>;
}
declare module 'send/index.js' {
  declare module.exports: $Exports<'send'>;
}
