// flow-typed signature: aadc6809448c68f9636a05d55445479e
// flow-typed version: <<STUB>>/useragent_v2.3.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'useragent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'useragent' {
  declare class OS {
    toString(): string;
    toVersion(): string;
    toJSON(): string;
  }

  declare class Device {
    toString(): string;
    toVersion(): string;
    toJSON(): string;
  }

  declare class Agent {
    toAgent(): string;
    toString(): string;
    toVersion(): string;
    toJSON(): string;
    os: OS;
    family: string;
    major: number;
    minor: number;
    patch: number;
  }
  declare export var parse: (string) => Agent;
}
