// flow-typed signature: 17ad7c412c2ef3f51f8ef57c736e956a
// flow-typed version: <<STUB>>/ws_v5.1.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ws' {
  import type {IncomingMessage} from 'http';
  import type {Socket} from 'net';
  declare class Server {
    constructor({
      noServer?: boolean,
    }): void;
    handleUpgrade(req: IncomingMessage, socket: Socket, head: Buffer, cb: (WebSocket) => void): void;
    clients: Array<WebSocket>;
  }
}
